name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: ['7.4', '8.0', '8.1']
        php_type: ['fpm', 'cli', 'supervisord']
        os_version: ['alpine']
    steps:
      - uses: e1himself/goss-installation-action@v1.0.4

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        env:
          IMAGE_NAMESPACE: wayofdev/php-dev
          TEMPLATE: ${{ matrix.php_version }}-${{ matrix.php_type }}-${{ matrix.os_version }}
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "IMAGE_NAMESPACE=${IMAGE_NAMESPACE}" >> $GITHUB_ENV
          echo "TEMPLATE=${TEMPLATE}" >> $GITHUB_ENV
          echo "VERSION=${RELEASE_VERSION:1}" >> $GITHUB_ENV

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAMESPACE }}
          tags: |
            type=raw,event=branch,value=latest
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false
            prefix=${{ matrix.php_version }}-${{ matrix.php_type }}-${{ matrix.os_version }}-

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      #
      ### For Cross Platform OSX builds uncomment these lines
      #
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      #   with:
      #     platforms: arm64
      #
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   with:
      #     install: true

      - name: Build and Export to Docker
        uses: docker/build-push-action@v2
        with:
          context: ./dist/dev/${{ env.TEMPLATE }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.IMAGE_TAG }}
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}

      - name: Test Docker Release Image
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_TAG=${{ env.IMAGE_NAMESPACE }}:${{ env.TEMPLATE }}-${{ env.VERSION }} make test

      - name: Test Docker Master Image
        if: success() && ! startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_TAG=${{ env.IMAGE_NAMESPACE }}:${{ env.TEMPLATE }}-latest make test

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./dist/dev/${{ env.TEMPLATE }}
          ### For Cross Platform OSX builds uncomment these lines
          # platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.IMAGE_TAG }}
          cache-to: type=inline
